apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: prometheus-adapter
    namespace: monitoring
    resourceVersion: "380403604"
    selfLink: /api/v1/namespaces/monitoring/serviceaccounts/prometheus-adapter
    uid: a51d5c64-b9e7-11ea-8a34-5a9b311e2d11
  
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: prometheus-k8s
    namespace: monitoring
  
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: prometheus-operator
      app.kubernetes.io/version: v0.34.1
    name: prometheus-operator
    namespace: monitoring
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
